-- Initial Database Schema for RentFair
-- Compatible with PostgreSQL and H2

CREATE TABLE IF NOT EXISTS search_queries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_query VARCHAR(500) NOT NULL,
    location VARCHAR(100),
    bhk VARCHAR(20),
    property_type VARCHAR(50),
    min_rent INTEGER,
    max_rent INTEGER,
    min_area INTEGER,
    max_area INTEGER,
    furnishing VARCHAR(50),
    result_count INTEGER,
    searched_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS rental_listings (
    id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    source_platform VARCHAR(100),
    source_url TEXT,
    snippet TEXT,
    locality VARCHAR(100),
    sub_locality VARCHAR(100),
    city VARCHAR(100),
    rent_amount INTEGER,
    deposit_amount INTEGER,
    bhk INTEGER,
    property_type VARCHAR(50),
    carpet_area_sqft INTEGER,
    furnishing VARCHAR(50),
    bathrooms INTEGER,
    price_per_sqft DOUBLE PRECISION,
    fairness_score INTEGER,
    fairness_category VARCHAR(50),
    variance_percentage DOUBLE PRECISION,
    confidence_score DOUBLE PRECISION,
    comparable_count INTEGER,
    fairness_explanation TEXT,
    is_statistical_outlier BOOLEAN,
    image_url TEXT,
    created_at TIMESTAMP NOT NULL
);
